name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SET UP Python
        uses: actions/setup-python@v2
        with:
          python-version: [3.8]
      - name: Run Python command
        run: |
          pip install --upgrade pip
          python3.8 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          echo "virtual env:" $env
