name: CI/CD Pipeline
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SET UP Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Python command
        run: |
          sudo apt install -y python3-pip
          sudo apt install -y python3-venv
          python3 -m venv env
          source env/bin/activate
          pip install -r requirements.txt
          echo "virtual env:" $env
